export const coffeeShops = [
  {
    name: 'Enderly Coffee Co',
    id: 1,
    companyId: 1,
    address: '2620 Tuckaseegee Rd',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28208,
    logo: '/images/logos/enderly-logo.png',
    websiteUrl: 'www.enderlycoffee.com',
    facebookLink: 'https://www.facebook.com/EnderlyCoffeeCo/',
    instagramLink: 'https://www.instagram.com/enderlycoffeeco/',
    twitterLink: 'https://twitter.com/enderlycoffeeco',
    roaster: 'Enderly Coffee Company',
    roasterId: 1,
    about: 'We are chill.  You will get to know our baristas, it is important to us.  Our Tagline is, "People First.  Coffee Always."  Open Monday-Saturday 7am-2pm. See you soon!',
    shopInfo: 'Parking lot is limited, but extra parking on State Street is available.  We do Cinnamon Roll Saturdays.  We have a Point System in our register, it\'s pretty darn generous.',
    currentFavoriteDrink: 'Cortado',
    infoFromShop: 1,
    neighboorhood: ''
  },
  {
    name: 'The Percantile and Creamery',
    id: 2,
    companyId: 2,
    address: '8635 Concord Mills Boulevard',
    city: 'Concord',
    state: 'NC',
    zipCode: 28027,
    logo: '/images/logos/percantile-logo.jpg',
    websiteUrl: 'http://www.thepercantileandcreamery.com/',
    twitterLink: '',
    facebookLink: 'https://www.facebook.com/thepercantileandcreamery/',
    instagramLink: 'https://www.instagram.com/the.percantile/',
    roaster: 'Lexington Coffee Roasters',
    roasterId: 2,
    about: '1920\'s themed Coffee and Ice Cream Shop nestled next to Concord Mills Mall.The Perc offers locally roasted coffee and couples it with the freshest ingredients and organic syrups to make a delicious cup, every time.  We offer premium ice cream made by Gifford\'s of Maine, a 5th generation ice cream maker that uses real fruit and milk from locally owned farms.  Check out our baked goods and chocolates too! Ask about our Birthday Parties and room rentals.',
    shopInfo: 'Tuesday-Family Board Game Night. Wednesday-Bingo Night. Friday-Open Mic. Sunday-Movie Matinee',
    currentFavoriteDrink: 'Bee\'s Knees',
    infoFromShop: 1,
    neighboorhood: ''
  },
  {
    name: 'Brakeman\'s Coffee & Supply',
    id: 3,
    companyId: 3,
    address: '225 N. Trade St',
    city: 'Matthews',
    state: 'NC',
    zipCode: 28105,
    logo: '/images/logos/brakemans-logo.png',
    websiteUrl: 'https://brakemanscoffee.com/',
    facebookLink: 'https://www.facebook.com/BrakemansCoffee/',
    instagramLink: 'https://www.instagram.com/brakemanscoffee/',
    twitterLink: '',
    roaster: 'Haerfest Coffee',
    roasterId: 3,
    about: 'We are committed to Keeping Matthews Slow. On the railroad, the Brakeman\'s job is to be aware as the train speeds down the tracks, making every passenger feel safe by slowing down at just the right moment. We are here to take care of you with efficiency and quality, all wrapped in a calming, hospitable environment. In a fast food world, we seek to offer slow culture coffee, with a chance to consider that \'faster, harder, more\' isn\'t always better. Brakeman\'s Coffee and Supply is a place where you can hit the brakes, and enjoy a cup of coffee in the midst of a busy week.',
    shopInfo: 'We have limited parking space behind our shop. Just a 1 minute walk away, the surrounding block has several parking spaces free for 2 hours. Parking is also available by the train tracks nearby, with 2 hour or unlimited time slots available.',
    currentFavoriteDrink: 'Rosemary\'s Brown Sugar',
    infoFromShop: 1,
    neighboorhood: ''
  },
  {
    name: 'Undercurrent Coffee',
    id: 4,
    companyId: 4,
    address: '2012 Commonwealth Ave',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28205,
    logo: '/images/logos/undercurrent-logo.png',
    websiteUrl: 'http://undercurrentcoffee.com/',
    facebookLink: 'https://www.facebook.com/undercurrent.coffee.clt/',
    twitterLink: 'https://twitter.com/undercurrentCLT',
    instagramLink: 'https://www.instagram.com/undercurrentcoffee/',
    roaster: 'Onyx Coffee Lab',
    roasterId: 4,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Central Coffee Co',
    id: 5,
    companyId: 5,
    address: '719 Louise Ave',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28204,
    logo: '/images/logos/centralcc-logo.png',
    websiteUrl: 'http://www.centralcoffeeco.com/',
    facebookLink: 'https://www.facebook.com/CentralCoffeeCo/',
    instagramLink: 'https://www.instagram.com/centralcoffee/',
    twitterLink: 'https://twitter.com/CentralCoffee',
    roaster: 'Joe Van Gogh',
    roasterId: 5,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Central Coffee Co',
    id: 6,
    companyId: 5,
    address: '1700 Camden Rd #101',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28203,
    logo: '/images/logos/centralcc-logo.png',
    websiteUrl: 'http://www.centralcoffeeco.com/',
    facebookLink: 'https://www.facebook.com/CentralCoffeeCo/',
    instagramLink: 'https://www.instagram.com/centralcoffee/',
    twitterLink: 'https://twitter.com/CentralCoffee',
    roaster: 'Joe Van Gogh',
    roasterId: 5,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Hex Espresso Bar',
    id: 7,
    companyId: 6,
    address: '125 Remount Rd',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28203,
    logo: '/images/logos/hex-logo.png',
    websiteUrl: 'https://hex.coffee/',
    facebookLink: 'https://www.instagram.com/hexcoffee/',
    instagramLink: 'https://www.facebook.com/HEXcoffeeclt/',
    twitterLink: 'https://twitter.com/hexcoffee',
    roaster: 'Hex Coffee',
    roasterId: 6,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Hex: The Roastery',
    id: 8,
    companyId: 6,
    address: '1824 Statesville Ave. 101',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28206,
    logo: '/images/logos/hex-logo.png',
    websiteUrl: 'https://hex.coffee/',
    facebookLink: 'https://www.instagram.com/hexcoffee/',
    instagramLink: 'https://www.facebook.com/HEXcoffeeclt/',
    twitterLink: 'https://twitter.com/hexcoffee',
    roaster: 'Hex Coffee',
    roasterId: 6,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Mugs Coffee',
    id: 9,
    companyId: 7,
    address: '5126 Park Rd #1',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28209,
    logo: '/images/logos/mugs-logo.png',
    websiteUrl: 'http://mugsofcharlotte.com/',
    facebookLink: 'https://www.facebook.com/Mugs-Coffee-188668647824076/',
    instagramLink: '',
    twitterLink: '',
    roaster: 'Magnolia Coffee',
    roasterId: 7,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 10,
    companyId: 8,
    address: '224 E 7th St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28202,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 10,
    companyId: 8,
    address: '222 S Church St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28202,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 11,
    companyId: 8,
    address: '2000 South Blvd',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28203,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 12,
    companyId: 8,
    address: '421 Providence Rd',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28207,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 13,
    companyId: 8,
    address: '2230 Park Rd',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28203,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Not Just Coffee',
    id: 14,
    companyId: 8,
    address: '1026 Jay St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28208,
    logo: '/images/logos/notjustcoffee-logo.png',
    websiteUrl: 'https://notjust.coffee/',
    facebookLink: '',
    instagramLink: 'https://www.instagram.com/notjustcoffee/',
    twitterLink: 'https://twitter.com/NotJCoffeeClt',
    roaster: 'Counter Culture Coffee',
    roasterId: 8,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  },
  {
    name: 'Queen City Grounds',
    id: 15,
    companyId: 9,
    address: '644 N Church St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 28202,
    logo: '/images/logos/qcgrounds-logo.png',
    websiteUrl: 'https://queencitygrounds.com/',
    facebookLink: 'https://www.facebook.com/qcgrounds/',
    instagramLink: 'https://www.instagram.com/queencitygrounds/',
    twitterLink: 'https://twitter.com/qcgrounds',
    roaster: 'Nightflyer Roastworks',
    roasterId: 9,
    about: '',
    shopInfo: '',
    currentFavoriteDrink: '',
    infoFromShop: 0,
    neighboorhood: ''
  }

  // {
  //   name: '',
  //   id: ,
  //   companyId: ,
  //   address: '',
  //   city: '',
  //   state: '',
  //   zipCode: ,
  //   logo: '/images/logos/',
  //   websiteUrl: '',
  //   facebookLink: '',
  //   instagramLink: '',
  //   twitterLink: '',
  //   roaster: '',
  //   roasterId: ,
  //   review: '',
  //   shopInfo: '',
  //   currentFavoriteDrink: '',
  //   infoFromShop: 0,
  //   neighboorhood: '',
  // }

  /**
   * Still need:
   *  Cafe Moka
   *  Amelie's French Bakery & Cafe
   *  Rhino Market
   *  Uptown Coffee Co
   *  Queen City Grounds
   *  Dunx
   *  Coco and the Director
   *  Smelly Cat Coffee House & Roastery
   *  Trade and Lore Coffee
   *  South End Grind
   *  Dilworth Coffee
   *  Okra
   *  Julia's Cafe & Books
   *  The Hobbyist
   *  Parliament Espresso & Coffee
   *  Crema Espresso Bar and Cafe
   *  Joe and Nosh
   *  Earl's Grocery
   *  Rush Espresso Cafe and Wine Bar
   *  Waterbean Coffee
   *  The People's Market
   *  Suffolk Punch
   *  Nova's Bakery
   *  Sunflour Baking Company
   *  Mayobird
   *  Lincoln's Haberdashery
   *  Common Market
   */
]

export default {
  coffeeShops
}
